### ISSUE TITLE
Gets confused when Terminal and Terminal Preview are both installed.

### ISSUE THREAD

**Issue by realparadyne** [mrange/windows-terminal-shader-gallery#4]
I have Terminal and Terminal Preview installed (and typically use the preview version).

I couldn't get to preview or see any shaders using either terminal version. There were no errors (used verbose mode too).

But if I manually copied the applied shader setting from the Terminal json settings file to the Terminal Preview settings file, then it started working.

**Comment by mrange** [comment]
in the verbose mode did you see if the path it wrote too was wrong? I know the preview terminal isn't working but I run both preview and released terminal and works for me.

The way I locate the setting file is very ad-hoc. I will check with terminal team if there's a better way

**Comment by realparadyne** [comment]
`PS C:\Users\david_8cja61n> wt-shader-tool -v
Starting front end
Downloading shader metadata from https://github.com/mrange/windows-terminal-shader-gallery/
Downloading and installing shader: fsharp-logo
Downloading shader from github: fsharp-logo
Writing shader to: C:\Users\david_8cja61n\AppData\Local\Temp\wt-shader-tool\downloads\fsharp-logo
Loading Windows Terminal settings from: C:\Users\david_8cja61n\AppData\Local\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\LocalState\settings.json
Saving Windows Terminal settings to: C:\Users\david_8cja61n\AppData\Local\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\LocalState\settings.json`

It seems to always write to the non-preview config file but at least on my system it doesn't show anything.  I can them manually copy the "experimental.pixelShaderPath" setting into the preview terminal json file and it then appears.  I was assuming from that, that the non-preview terminal doesn't actually support shaders?

**Comment by mrange** [comment]
what if you add it to the standard terminal? What version is the standard terminal? does it come with the OS or did you install it through the store?
Perhaps I should add a command line option to look for the preview version instead?

WDYT?

**Comment by realparadyne** [comment]
Terminal 1.15.2875.0
Terminal Preview 1.16.2642.0
It's a Windows 11 22H2 which I think started having Terminal as standard?

An option sounds good, or always apply it to both?

I was copying the setting from the Terminal config file to the Terminal Preview, but on Terminal the backgrounds just stayed black. Restarting it made no difference.  But I'll give it all a try on my home system later and see if I get the same behaviours.

**Comment by mrange** [comment]
I just added a -p option to the tip. Is it possible for you to clone and try it out?

`dotnet run -- -p`

**Comment by mrange** [comment]
it's possible Windows Terminal shipped with W11 don't have shader support. I can understand if they are a bit careful with feautres like that in stuff that is shipped with windows

**Comment by mrange** [comment]
Latest release has `-p` flag to set background shader in preview version of Windows Terminal: https://github.com/mrange/windows-terminal-shader-gallery/releases/tag/v0.0.5

**Comment by mrange** [comment]
Please reopen if the v0.0.5 don't fix the issue for you.
